// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gstake/lscosmos/v1beta1/governance_proposal.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MinDepositAndFeeChangeProposal struct {
	Title               string                                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description         string                                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	MinDeposit          github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=min_deposit,json=minDeposit,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"min_deposit"`
	GstakeDepositFee    github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=gstake_deposit_fee,json=gstakeDepositFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"gstake_deposit_fee"`
	GstakeRestakeFee    github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,5,opt,name=gstake_restake_fee,json=gstakeRestakeFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"gstake_restake_fee"`
	GstakeUnstakeFee    github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=gstake_unstake_fee,json=gstakeUnstakeFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"gstake_unstake_fee"`
	GstakeRedemptionFee github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,7,opt,name=gstake_redemption_fee,json=gstakeRedemptionFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"gstake_redemption_fee"`
}

func (m *MinDepositAndFeeChangeProposal) Reset()      { *m = MinDepositAndFeeChangeProposal{} }
func (*MinDepositAndFeeChangeProposal) ProtoMessage() {}
func (*MinDepositAndFeeChangeProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c14992650426d50, []int{0}
}
func (m *MinDepositAndFeeChangeProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MinDepositAndFeeChangeProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MinDepositAndFeeChangeProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MinDepositAndFeeChangeProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinDepositAndFeeChangeProposal.Merge(m, src)
}
func (m *MinDepositAndFeeChangeProposal) XXX_Size() int {
	return m.Size()
}
func (m *MinDepositAndFeeChangeProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_MinDepositAndFeeChangeProposal.DiscardUnknown(m)
}

var xxx_messageInfo_MinDepositAndFeeChangeProposal proto.InternalMessageInfo

type GstakeFeeAddressChangeProposal struct {
	Title            string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description      string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	GstakeFeeAddress string `protobuf:"bytes,3,opt,name=gstake_fee_address,json=gstakeFeeAddress,proto3" json:"gstake_fee_address,omitempty"`
}

func (m *GstakeFeeAddressChangeProposal) Reset()      { *m = GstakeFeeAddressChangeProposal{} }
func (*GstakeFeeAddressChangeProposal) ProtoMessage() {}
func (*GstakeFeeAddressChangeProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c14992650426d50, []int{1}
}
func (m *GstakeFeeAddressChangeProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GstakeFeeAddressChangeProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GstakeFeeAddressChangeProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GstakeFeeAddressChangeProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GstakeFeeAddressChangeProposal.Merge(m, src)
}
func (m *GstakeFeeAddressChangeProposal) XXX_Size() int {
	return m.Size()
}
func (m *GstakeFeeAddressChangeProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_GstakeFeeAddressChangeProposal.DiscardUnknown(m)
}

var xxx_messageInfo_GstakeFeeAddressChangeProposal proto.InternalMessageInfo

type AllowListedValidatorSetChangeProposal struct {
	Title                 string                `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description           string                `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AllowListedValidators AllowListedValidators `protobuf:"bytes,3,opt,name=allow_listed_validators,json=allowListedValidators,proto3" json:"allow_listed_validators"`
}

func (m *AllowListedValidatorSetChangeProposal) Reset()      { *m = AllowListedValidatorSetChangeProposal{} }
func (*AllowListedValidatorSetChangeProposal) ProtoMessage() {}
func (*AllowListedValidatorSetChangeProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c14992650426d50, []int{2}
}
func (m *AllowListedValidatorSetChangeProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AllowListedValidatorSetChangeProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AllowListedValidatorSetChangeProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AllowListedValidatorSetChangeProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowListedValidatorSetChangeProposal.Merge(m, src)
}
func (m *AllowListedValidatorSetChangeProposal) XXX_Size() int {
	return m.Size()
}
func (m *AllowListedValidatorSetChangeProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowListedValidatorSetChangeProposal.DiscardUnknown(m)
}

var xxx_messageInfo_AllowListedValidatorSetChangeProposal proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MinDepositAndFeeChangeProposal)(nil), "gstake.lscosmos.v1beta1.MinDepositAndFeeChangeProposal")
	proto.RegisterType((*GstakeFeeAddressChangeProposal)(nil), "gstake.lscosmos.v1beta1.GstakeFeeAddressChangeProposal")
	proto.RegisterType((*AllowListedValidatorSetChangeProposal)(nil), "gstake.lscosmos.v1beta1.AllowListedValidatorSetChangeProposal")
}

func init() {
	proto.RegisterFile("gstake/lscosmos/v1beta1/governance_proposal.proto", fileDescriptor_9c14992650426d50)
}

var fileDescriptor_9c14992650426d50 = []byte{
	// 542 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x6d, 0x48, 0x0b, 0x5c, 0x16, 0x64, 0x52, 0x35, 0x74, 0xb8, 0x54, 0x95, 0xa8, 0x58,
	0x62, 0x2b, 0x20, 0x16, 0xc4, 0x92, 0x10, 0x05, 0x55, 0x02, 0x81, 0x52, 0xc1, 0x00, 0x42, 0xd6,
	0xc5, 0xf7, 0xea, 0x1e, 0x75, 0xee, 0xac, 0xbb, 0x6b, 0x80, 0x8d, 0x8f, 0xc0, 0xc8, 0xd8, 0x11,
	0x31, 0xf7, 0x43, 0x64, 0xac, 0xba, 0x80, 0x18, 0x2a, 0x48, 0x16, 0xbe, 0x01, 0x2b, 0x8a, 0xef,
	0xec, 0x18, 0xa9, 0x1d, 0x2a, 0x79, 0xba, 0xc4, 0xef, 0xbd, 0xff, 0xef, 0xff, 0xee, 0x9e, 0x1e,
	0xea, 0xc4, 0x4a, 0x93, 0x03, 0x08, 0x12, 0x15, 0x09, 0x35, 0x16, 0x2a, 0x98, 0x74, 0x46, 0xa0,
	0x49, 0x27, 0x88, 0xc5, 0x04, 0x24, 0x27, 0x3c, 0x82, 0x30, 0x95, 0x22, 0x15, 0x8a, 0x24, 0x7e,
	0x2a, 0x85, 0x16, 0xde, 0xba, 0x29, 0xf1, 0xf3, 0x12, 0xdf, 0x96, 0x6c, 0x34, 0x62, 0x11, 0x8b,
	0x2c, 0x27, 0x58, 0xfc, 0x32, 0xe9, 0x1b, 0xd8, 0x0a, 0x8f, 0x88, 0x82, 0x42, 0x3d, 0x12, 0x8c,
	0xdb, 0xf8, 0x6d, 0x13, 0x0f, 0x4d, 0xa1, 0x95, 0x34, 0xa1, 0xed, 0x8b, 0xcc, 0x15, 0xe8, 0x2c,
	0x6f, 0xeb, 0x6f, 0x0d, 0xe1, 0x67, 0x8c, 0xf7, 0x21, 0x15, 0x8a, 0xe9, 0x2e, 0xa7, 0x03, 0x80,
	0xc7, 0xfb, 0x84, 0xc7, 0xf0, 0xc2, 0x5a, 0xf7, 0x1a, 0x68, 0x45, 0x33, 0x9d, 0x40, 0xd3, 0xdd,
	0x74, 0xef, 0xde, 0x18, 0x9a, 0x3f, 0xde, 0x26, 0xaa, 0x53, 0x50, 0x91, 0x64, 0xa9, 0x66, 0x82,
	0x37, 0xaf, 0x64, 0xb1, 0xf2, 0x27, 0xef, 0x2d, 0xaa, 0x8f, 0x19, 0x0f, 0xa9, 0x91, 0x6e, 0x5e,
	0x5d, 0x64, 0xf4, 0x1e, 0x4d, 0xcf, 0x5a, 0xce, 0xcf, 0xb3, 0xd6, 0x76, 0xcc, 0xf4, 0xfe, 0xe1,
	0xc8, 0x8f, 0xc4, 0xd8, 0x1a, 0xb7, 0x47, 0x5b, 0xd1, 0x83, 0x40, 0x7f, 0x4c, 0x41, 0xf9, 0x3b,
	0x5c, 0x9f, 0x1e, 0xb7, 0x91, 0xf5, 0xbb, 0xc3, 0xf5, 0x10, 0x8d, 0x0b, 0xab, 0xde, 0x3b, 0xe4,
	0x99, 0x1e, 0x73, 0x42, 0xb8, 0x07, 0xd0, 0xac, 0x5d, 0x9a, 0xd2, 0x87, 0xa8, 0x44, 0xe9, 0x43,
	0x34, 0xbc, 0x69, 0x74, 0x2d, 0x68, 0x00, 0x50, 0x62, 0x49, 0x30, 0xe7, 0x82, 0xb5, 0x52, 0x1d,
	0x6b, 0x68, 0x64, 0xff, 0x67, 0x1d, 0xf2, 0x25, 0x6b, 0xb5, 0x3a, 0xd6, 0x4b, 0x5e, 0xb0, 0x52,
	0xb4, 0x56, 0xf4, 0x45, 0x61, 0x9c, 0xbd, 0x5b, 0x86, 0xbb, 0x56, 0x01, 0xee, 0x56, 0xde, 0x5a,
	0xae, 0x3c, 0x00, 0x78, 0x78, 0xfd, 0xcb, 0x51, 0xcb, 0xf9, 0x73, 0xd4, 0x72, 0xb6, 0xbe, 0xb9,
	0x08, 0x3f, 0xc9, 0x9d, 0x74, 0x29, 0x95, 0xa0, 0x54, 0x45, 0x93, 0x37, 0x28, 0xae, 0x70, 0x0f,
	0x20, 0x24, 0x46, 0xdb, 0x0e, 0x60, 0xf3, 0xf4, 0xb8, 0xdd, 0xb0, 0x2e, 0x2d, 0x75, 0x57, 0x4b,
	0xc6, 0xe3, 0xfc, 0x7a, 0x96, 0x6e, 0x4a, 0x66, 0xbf, 0xbb, 0xe8, 0x4e, 0x37, 0x49, 0xc4, 0xfb,
	0xa7, 0x4c, 0x69, 0xa0, 0xaf, 0x48, 0xc2, 0x28, 0xd1, 0x42, 0xee, 0x82, 0xae, 0xc8, 0x73, 0x82,
	0xd6, 0xc9, 0x02, 0x10, 0x26, 0x19, 0x21, 0x9c, 0xe4, 0x08, 0x63, 0xbc, 0x7e, 0xcf, 0xf7, 0x2f,
	0x58, 0x1e, 0xfe, 0x79, 0xc6, 0x54, 0xaf, 0xb6, 0x78, 0xbc, 0xe1, 0x1a, 0x39, 0x2f, 0xb8, 0xec,
	0xac, 0xf7, 0x66, 0xfa, 0x1b, 0x3b, 0x9f, 0x66, 0xd8, 0xf9, 0x3a, 0xc3, 0xee, 0x74, 0x86, 0xdd,
	0x93, 0x19, 0x76, 0x7f, 0xcd, 0xb0, 0xfb, 0x79, 0x8e, 0x9d, 0x93, 0x39, 0x76, 0x7e, 0xcc, 0xb1,
	0xf3, 0xfa, 0x41, 0x69, 0x02, 0x62, 0xc9, 0x28, 0x93, 0x82, 0x3f, 0xe7, 0x10, 0x18, 0x4b, 0x6d,
	0x4e, 0x34, 0x9b, 0x40, 0xf0, 0x61, 0xb9, 0x6e, 0xb2, 0xa1, 0x18, 0xad, 0x66, 0x4b, 0xe6, 0xfe,
	0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x57, 0x15, 0x2a, 0x44, 0x2b, 0x05, 0x00, 0x00,
}

func (m *MinDepositAndFeeChangeProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MinDepositAndFeeChangeProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MinDepositAndFeeChangeProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.GstakeRedemptionFee.Size()
		i -= size
		if _, err := m.GstakeRedemptionFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernanceProposal(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.GstakeUnstakeFee.Size()
		i -= size
		if _, err := m.GstakeUnstakeFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernanceProposal(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.GstakeRestakeFee.Size()
		i -= size
		if _, err := m.GstakeRestakeFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernanceProposal(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.GstakeDepositFee.Size()
		i -= size
		if _, err := m.GstakeDepositFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernanceProposal(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.MinDeposit.Size()
		i -= size
		if _, err := m.MinDeposit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernanceProposal(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintGovernanceProposal(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintGovernanceProposal(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GstakeFeeAddressChangeProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GstakeFeeAddressChangeProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GstakeFeeAddressChangeProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GstakeFeeAddress) > 0 {
		i -= len(m.GstakeFeeAddress)
		copy(dAtA[i:], m.GstakeFeeAddress)
		i = encodeVarintGovernanceProposal(dAtA, i, uint64(len(m.GstakeFeeAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintGovernanceProposal(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintGovernanceProposal(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AllowListedValidatorSetChangeProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AllowListedValidatorSetChangeProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AllowListedValidatorSetChangeProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AllowListedValidators.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGovernanceProposal(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintGovernanceProposal(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintGovernanceProposal(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGovernanceProposal(dAtA []byte, offset int, v uint64) int {
	offset -= sovGovernanceProposal(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MinDepositAndFeeChangeProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovGovernanceProposal(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovGovernanceProposal(uint64(l))
	}
	l = m.MinDeposit.Size()
	n += 1 + l + sovGovernanceProposal(uint64(l))
	l = m.GstakeDepositFee.Size()
	n += 1 + l + sovGovernanceProposal(uint64(l))
	l = m.GstakeRestakeFee.Size()
	n += 1 + l + sovGovernanceProposal(uint64(l))
	l = m.GstakeUnstakeFee.Size()
	n += 1 + l + sovGovernanceProposal(uint64(l))
	l = m.GstakeRedemptionFee.Size()
	n += 1 + l + sovGovernanceProposal(uint64(l))
	return n
}

func (m *GstakeFeeAddressChangeProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovGovernanceProposal(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovGovernanceProposal(uint64(l))
	}
	l = len(m.GstakeFeeAddress)
	if l > 0 {
		n += 1 + l + sovGovernanceProposal(uint64(l))
	}
	return n
}

func (m *AllowListedValidatorSetChangeProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovGovernanceProposal(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovGovernanceProposal(uint64(l))
	}
	l = m.AllowListedValidators.Size()
	n += 1 + l + sovGovernanceProposal(uint64(l))
	return n
}

func sovGovernanceProposal(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGovernanceProposal(x uint64) (n int) {
	return sovGovernanceProposal(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MinDepositAndFeeChangeProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGovernanceProposal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MinDepositAndFeeChangeProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MinDepositAndFeeChangeProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernanceProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernanceProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDeposit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernanceProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinDeposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GstakeDepositFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernanceProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GstakeDepositFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GstakeRestakeFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernanceProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GstakeRestakeFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GstakeUnstakeFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernanceProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GstakeUnstakeFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GstakeRedemptionFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernanceProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GstakeRedemptionFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGovernanceProposal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GstakeFeeAddressChangeProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGovernanceProposal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GstakeFeeAddressChangeProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GstakeFeeAddressChangeProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernanceProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernanceProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GstakeFeeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernanceProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GstakeFeeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGovernanceProposal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AllowListedValidatorSetChangeProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGovernanceProposal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AllowListedValidatorSetChangeProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AllowListedValidatorSetChangeProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernanceProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernanceProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowListedValidators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernanceProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AllowListedValidators.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGovernanceProposal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGovernanceProposal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGovernanceProposal(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGovernanceProposal
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGovernanceProposal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGovernanceProposal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGovernanceProposal
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGovernanceProposal
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGovernanceProposal
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGovernanceProposal        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGovernanceProposal          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGovernanceProposal = fmt.Errorf("proto: unexpected end of group")
)
